export const ActionTypes = {
     PAGE_LIST_USER: 'PAGE_LIST_USER',
     PAGE_LIST_POST: 'PAGE_LIST_POST',
     PAGE_LIST_ALBUMS: 'PAGE_LIST_ALBUMS',
     PAGE_DETAIL_POST: 'PAGE_DETAIL_POST',
     PAGE_DETAIL_ALBUM: 'PAGE_DETAIL_ALBUM',
     PAGE_LIST_COMMENT: 'PAGE_LIST_COMMENT',
     PAGE_EDIT_POST: 'PAGE_EDIT_POST',
     PAGE_EDIT_DETAIL_POST: 'PAGE_EDIT_DETAIL_POST',
     PAGE_LIST_PHOTOS: 'PAGE_LIST_PHOTOS',
     PAGE_GET_EDIT_POST: 'PAGE_GET_EDIT_POST',
     PAGE_GET_DETAIL_PHOTO: 'PAGE_GET_DETAIL_PHOTO',
};

export default ActionTypes;
